agregado dos tipos de deploy

diff --git a/.github/workflows/deploylaravel.yml b/.github/workflows/deploylaravel.yml
--- a/.github/workflows/deploylaravel.yml
+++ b/.github/workflows/deploylaravel.yml
@@ -233,8 +233,42 @@ jobs:
           git push origin HEAD:${RAMA}
   #####################################################################
   ############# Despliegue al clúster Kubernetes ######################
-  deploy:
-    name: 📦 Deploy al clúster Kubernetes
+  deploy-k8s:
+    name: 📦 Deploy Manifiesto al k8s
+    runs-on: ubuntu-latest
+    needs: [build, lint]
+    if: needs.lint.result == 'success'
+    outputs:
+      status: ${{ steps.k8s_apply.outputs.status }}
+    steps:
+      - name: Checkout del repositorio
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.GH_PAT }}
+      - name: Descargar manifiesto generado
+        uses: actions/download-artifact@v4
+        with:
+          name: kustomize-manifests
+          path: .
+      - name: Configurar Kubeconfig
+        run: |
+          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
+      - name: Aplicar manifiesto al clúster
+        id: k8s_apply
+        env:
+          KUBECONFIG: kubeconfig.yaml
+        run: |
+          set +e
+          echo "🔁 Aplicando manifiesto kustomize-output.yaml al clúster..."
+          echo "Aplicando imagen: ${{ needs.build.outputs.tag || 'imagen sin cambios' }}"
+          if kubectl apply -f kustomize-output.yaml; then
+            echo "status=success" >> "$GITHUB_OUTPUT"
+          else
+            echo "status=failure" >> "$GITHUB_OUTPUT"
+            exit 1
+          fi
+  deploy-image:
+    name: 📦 Deploy Imagen Nueva al k8s
     runs-on: ubuntu-latest
     needs: [build, lint, update-kustomization]
     if: needs.lint.result == 'success'
